"""Regression guard: literature_survey mode has no final-synthesis LLM call.

The survey report is generated by deterministic text aggregation
(`_generate_survey_report`). The three LLM calls in this mode
(_analyze_batch, _identify_themes, _assign_papers_to_themes) are
intermediate paper-metadata processing and operate on abstracts only —
no DocumentChunk retrieval surface bearing figure_refs is involved.

These tests pin that contract so any future addition of a true
user-facing synthesis call must explicitly decide how to wire the
multimodal hook (perspicacite.rag.multimodal.wrap_messages_for_chunks).
"""

from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest


def test_marker_comment_present():
    """The scoped-out marker in _generate_survey_report must remain."""
    src = Path("src/perspicacite/rag/modes/literature_survey.py").read_text()
    assert "Capsule Cycle B" in src
    assert "wrap_messages_for_chunks" in src


@pytest.mark.asyncio
async def test_survey_report_makes_no_llm_call():
    """_generate_survey_report is purely deterministic — never calls llm.complete."""
    from perspicacite.rag.modes.literature_survey import (
        LiteratureSurveyRAGMode,
        PaperCandidate,
        SurveySession,
        Theme,
    )

    cfg = MagicMock()
    cfg.rag_modes.literature_survey = MagicMock(spec=[])
    mode = LiteratureSurveyRAGMode(cfg)

    paper = PaperCandidate(
        id="p1",
        title="P1",
        authors=["A B"],
        year=2024,
        abstract="abs",
        doi="10.1/x",
        citation_count=5,
    )
    session = SurveySession(
        session_id="s1",
        query="test query",
        papers=[paper],
        themes=[Theme(name="t", description="d")],
        selected_papers=["p1"],
    )

    llm = MagicMock()
    llm.complete = AsyncMock(side_effect=AssertionError("should not be called"))

    result = await mode._generate_survey_report(session, list(session.papers), llm)
    assert isinstance(result, str)
    assert "test query" in result
    llm.complete.assert_not_called()
